name: Setup
description: Nix and Rust cache setup

inputs:
  rust-cache:
    description: Enable Rust cache
    default: 'true'
  rust-cache-shared-key:
    description: Shared key for Rust cache
    default: ''
  nix-develop-arguments:
    description: Arguments to pass to nix develop
    default: ''

runs:
  using: composite
  steps:
    - uses: NixOS/nix-installer-action@main
      with:
        extra-conf: |
          auto-optimise-store = false
          cores = 0
          max-substitution-jobs = 32
          http-connections = 50
          download-buffer-size = 2560000
    - uses: nix-community/cache-nix-action@main
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.rust-cache == 'true' }}
      with:
        shared-key: ${{ inputs.rust-cache-shared-key }}
    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: ${{ inputs.nix-develop-arguments }}
