#!/usr/bin/env bash
#
# bootstrap.sh — Multi-stage bootstrap for the Nexus self-hosted compiler (nxc/)
#
# Stage 0: Rust compiler (nexus build) compiles nxc/driver.nx → stage0.wasm
# Stage 1: Run stage0.wasm (nexus exec) to compile nxc/driver.nx → stage1.wasm
# Stage 2: Run stage1.wasm (nexus exec) to compile nxc/driver.nx → stage2.wasm
# Verify:  stage1.wasm == stage2.wasm (fixed point)
#
# Usage: ./bootstrap.sh [--ci]
#   --ci    Strict mode for CI: fail on stage2 failure or non-identical output
#
set -euo pipefail

CI_MODE=false
for arg in "$@"; do
  case "$arg" in
    --ci) CI_MODE=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

NEXUS="${NEXUS:-./target/release/nexus}"
NXC_ENTRY="nxc/driver.nx"
BUILD_DIR="bootstrap_out"
NEXUS_EXEC_FLAGS="--allow-fs --allow-console --allow-proc --allow-random --allow-clock"
NEXUS_BUILD_FLAGS=""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

info()  { printf "${CYAN}[bootstrap]${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}[bootstrap]${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}[bootstrap]${RESET} %s\n" "$*"; }
fail()  { printf "${RED}[bootstrap]${RESET} %s\n" "$*" >&2; exit 1; }

# ─── Ensure the Rust compiler is built ─────────────────────────────────────

if [[ ! -x "$NEXUS" ]]; then
  info "Building Rust compiler (cargo build --release)..."
  cargo build --release
fi

[[ -x "$NEXUS" ]] || fail "Rust compiler not found at $NEXUS"
info "Using Rust compiler: $NEXUS"

mkdir -p "$BUILD_DIR"

# ─── Helper: generate nxc executable wrapper ─────────────────────────────
# Builds a component WASM via `nexus build` and extracts wasmtime flags from
# --explain-capabilities output, then generates a `nxc` bash wrapper script.

generate_nxc_wrapper() {
  local component="$BUILD_DIR/nxc_component.wasm"
  info "Building component WASM for standalone execution..."
  local caps_json
  caps_json=$("$NEXUS" build "$NXC_ENTRY" \
    --explain-capabilities wasmtime \
    --explain-capabilities-format json \
    -o "$component" 2>&1)

  # Install the component WASM (self-contained, runnable by wasmtime)
  cp "$component" nxc_driver.wasm
  ok "Installed component: nxc_driver.wasm ($(wc -c < nxc_driver.wasm | tr -d ' ') bytes)"

  # Parse wasmtime flags from JSON:
  #   {"file":"...","capabilities":[...],"wasmtime":{"command":"...","flags":["--dir","."]}}
  local wt_flags=""
  # Extract the flags array values: "flag1","flag2" → flag1 flag2
  local flags_csv
  flags_csv=$(echo "$caps_json" | sed 's/.*"flags":\[\([^]]*\)\].*/\1/')
  if [[ "$flags_csv" != "$caps_json" ]]; then
    # Parse comma-separated quoted strings into shell arguments
    wt_flags=$(echo "$flags_csv" | tr ',' '\n' | tr -d '"' | tr '\n' ' ' | sed 's/ *$//')
  fi

  local wrapper="nxc_driver"
  cat > "$wrapper" <<WRAPPER
#!/usr/bin/env bash
#
# nxc — Nexus self-hosted compiler
# Generated by bootstrap.sh
#
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
exec wasmtime run -W max-wasm-stack=67108864,tail-call=y ${wt_flags:+${wt_flags} }"\$SCRIPT_DIR/nxc_driver.wasm" "\$@"
WRAPPER
  chmod +x "$wrapper"
  ok "Generated wrapper: $wrapper"
}

# ─── Stage 0: Rust compiler → stage0.wasm ─────────────────────────────────
# Try to reuse `nexus nxc` auto-cache (target/nxc/nxc_driver.wasm).
# If the cache is valid, copy it as stage0 instead of recompiling.

STAGE0="$BUILD_DIR/stage0.wasm"
NXC_CACHE="target/nxc/nxc_driver.wasm"

# Trigger cache build (nxc with no args exits with usage, but populates cache).
if "$NEXUS" nxc >/dev/null 2>&1 || [[ -f "$NXC_CACHE" ]]; then
  info "Stage 0: reusing cached nxc_driver.wasm"
  cp "$NXC_CACHE" "$STAGE0"
else
  info "Stage 0: nexus build $NXC_ENTRY → $STAGE0"
  "$NEXUS" build $NEXUS_BUILD_FLAGS "$NXC_ENTRY" -o "$STAGE0"
fi
ok "Stage 0 complete: $STAGE0 ($(wc -c < "$STAGE0" | tr -d ' ') bytes)"

# ─── Stage 1: stage0.wasm compiles nxc → stage1.wasm ──────────────────────

STAGE1="$BUILD_DIR/stage1.wasm"
info "Stage 1: nexus exec $STAGE0 -- $NXC_ENTRY $STAGE1"
"$NEXUS" exec $NEXUS_EXEC_FLAGS "$STAGE0" -- "$NXC_ENTRY" --verbose "$STAGE1"
ok "Stage 1 complete: $STAGE1 ($(wc -c < "$STAGE1" | tr -d ' ') bytes)"

# ─── Bundle stage1 with stdlib ─────────────────────────────────────────────
# Stage1 is a core WASM that imports stdlib/stdlib.wasm.
# Bundle it so stage2 can run without external dependencies.

WASM_MERGE="${NEXUS_WASM_MERGE:-wasm-merge}"
STAGE1_BUNDLED="$BUILD_DIR/stage1_bundled.wasm"
HOST_STUB_WAT="$(pwd)/nxlib/stdlib/nexus_host_stub.wat"
HOST_STUB_WASM="$(pwd)/stdlib/nexus_host_stub.wasm"
if [[ -f "$HOST_STUB_WAT" && ! -f "$HOST_STUB_WASM" ]]; then
  if command -v wat2wasm >/dev/null 2>&1; then
    info "Compiling nexus_host_stub.wat → .wasm"
    wat2wasm "$HOST_STUB_WAT" -o "$HOST_STUB_WASM"
  fi
fi
if command -v "$WASM_MERGE" >/dev/null 2>&1 || [[ -x "$WASM_MERGE" ]]; then
  info "Bundling stage1 with stdlib..."
  "$WASM_MERGE" "$STAGE1" __main \
    "$(pwd)/stdlib/stdlib.wasm" "stdlib/stdlib.wasm" \
    "$(pwd)/stdlib/nexus_host_stub.wasm" "nexus:cli/nexus-host" \
    --all-features --enable-tail-call --rename-export-conflicts \
    -o "$STAGE1_BUNDLED"
  ok "Bundled: $STAGE1_BUNDLED ($(wc -c < "$STAGE1_BUNDLED" | tr -d ' ') bytes)"
else
  warn "wasm-merge not found — skipping bundle, stage2 may fail"
  cp "$STAGE1" "$STAGE1_BUNDLED"
fi

# ─── Stage 2: stage1.wasm compiles nxc → stage2.wasm ──────────────────────

STAGE2="$BUILD_DIR/stage2.wasm"
info "Stage 2: nexus exec $STAGE1_BUNDLED -- $NXC_ENTRY $STAGE2"
if "$NEXUS" exec $NEXUS_EXEC_FLAGS "$STAGE1_BUNDLED" -- "$NXC_ENTRY" --verbose "$STAGE2" 2>&1; then
  ok "Stage 2 complete: $STAGE2 ($(wc -c < "$STAGE2" | tr -d ' ') bytes)"
else
  if [[ "$CI_MODE" == true ]]; then
    fail "Stage 2 failed — nxc-produced WASM is not self-executable."
  fi
  warn "Stage 2 failed — nxc-produced WASM not yet self-executable."
  warn "Stage 1 output is still valid (compiled by the Rust-built stage0)."
  generate_nxc_wrapper
  exit 0
fi

# ─── Verify fixed point ───────────────────────────────────────────────────

info "Verifying fixed point: stage1 == stage2"
if cmp -s "$STAGE1" "$STAGE2"; then
  ok "Fixed point reached! stage1.wasm and stage2.wasm are identical."
  ok "The self-hosted compiler is verified."
else
  if [[ "$CI_MODE" == true ]]; then
    S1_SIZE=$(wc -c < "$STAGE1" | tr -d ' ')
    S2_SIZE=$(wc -c < "$STAGE2" | tr -d ' ')
    info "stage1: $S1_SIZE bytes, stage2: $S2_SIZE bytes"
    fail "Fixed point NOT reached — stage1.wasm and stage2.wasm differ."
  fi
  warn "stage1.wasm and stage2.wasm differ — not yet at fixed point."
  warn "This is expected while nxc codegen is still maturing."
fi

# ─── Generate nxc executable wrapper ─────────────────────────────────────

generate_nxc_wrapper
