(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $exit (param i32)))
  (type $ft (func))
  (type $ct (cont $ft))
  (tag $t)
  (func $body (suspend $t))
  (elem declare func $body)
  (memory (export "memory") 1)
  (func (export "_start")
    (local $k (ref null $ct))
    (block $h (result (ref $ct))
      (resume $ct (on $t $h) (cont.new $ct (ref.func $body)))
      (call $exit (i32.const 7))
      (unreachable))
    (local.set $k)
    (resume $ct (local.get $k))
    (call $exit (i32.const 1))))
