name: Build Cargo Dependencies

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          rust-cache-shared-key: cargo-deps
      - name: Build dependencies
        run: cargo build --release --tests
